# Generated by Django 6.0.1 on 2026-07-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
