# Generated by Django 5.2.15 on 2026-07-12 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Fleet Manager', 'Fleet Manager'), ('Driver', 'Driver'), ('Safety Officer', 'Safety Officer'), ('Financial Analyst', 'Financial Analyst'), ('Admin', 'Admin')], default='Driver', max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
