# Generated by Django 5.2.15 on 2026-07-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Trip Revenue for ROI calculation', max_digits=12),
        ),
    ]
