# Generated by Django 6.0.7 on 2026-07-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_security_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='estimated_fuel_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Auto-calculated estimated fuel cost (₹)', max_digits=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('CNG', 'CNG')], default='Diesel', help_text='Type of fuel used', max_length=10),
        ),
    ]
